---
title: "hw9-report"
author: "Jack McShane"
date: '2022-04-23'
output: 
  pdf_document:
    extra_dependencies: ["amsmath", "amssymb", "ulem", "enumerate", "listings"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Let $Y_1, Y_2, \dots, Y_n \sim_{iid} N(\theta, \sigma^2)$ where $\sigma^2$ is known. Consider $H_0: \theta \leq \theta_0$ vs. $H_1: \theta > \theta_0$.

\

## (a) What would be Type I Error? What would be Type II Error?

Type I error involves selecting or accepting the wrong hypothesis when the evidence does not support it. An example of this kind of error would be a company pushing the idea that their drug is better than another even though the evidence supports the opposite conclusion.

\

Type II error involves selecting the wrong hypothesis due to a lack of data (or if the data is not representative). If there is not enough data to support the new hypothesis even though it is the correct one, our test procedure could lead one to select the incorrect hypothesis.

\

## (b) In HW8, we show that the likelihood ratio test procedure is to reject $H_0$ if

\[ z = \frac{ \bar{y} - \theta_0 }{ \sigma / \sqrt{n} } \geq k_1 = \sqrt{-2log(k)} \]

## The power function of this test is:

\[ \gamma(\theta) = P(N(0,1) \geq k_1 + \frac{\theta_0 - \theta}{\sigma/\sqrt{n}}) \]

## Let $\theta_0$ = 105, $\sigma$ = 10, n = 100 and $k_1$ = 1.8, plot this function, and comment on your plot.

\

## (c) For this test, what is the probability of Type I Error when $\theta$ = 105?

\

## (d) For this test, what is the probability of Type II Error when $\theta$ = 110? What is the power of rejecting $H_0$ when $\theta$ = 110?

\

## (e) If we set the significance level $\alpha$ = 0.05, what is $k_1$?

\

## (f) For this test procedure with $\alpha$ = 0.05, what sample size $n$ is necessary to ensure that the power of rejecting $H_0$ at $\theta$ = 108 is at least 80%?

\
\

## 2. Consider the carprice example from 'Notes 7'.

\

## (a) What is the $\hat{\beta_1}$? How do you interpret this number?

\

## (b) To test $H_0: \beta_1 = 0$ vs $H_1: \beta_1 \neq 0$, what is the P-value? What is your conclusion?

\

## (c) Based on this output, what is the prediction of the average car price for a 3-year-old car with mileage of 25,000?

\
\

## 3. Consider the Default example from 'Notes 8'.

\

## (a) What is the $\hat{\beta_1}$? How do you interpret this number?

\

## (b) What is your prediction of Default for someone who is a student, with balance of 800 and income of 15,000?

\

## (c) To test $H_0: \beta_1$ = 0 vs $H_1: \beta_1 \neq 0$, what is the p-value? What is your conclusion?